### ISSUE TITLE
Spelling mistake in 'learn more about it in our documentation'. Location, Tables Tab --> Tables

### ISSUE THREAD

**Issue by mohitsahasrabudhe** [Nebo15/gandalf.web#165]
The sentence -> You can lean more about them in our documentation.
should actually be -> You can learn more about them in our documentation.

![image](https://user-images.githubusercontent.com/24694554/38305890-30df6690-382c-11e8-86c8-2a0feabc70fa.png)

**Comment by AndrewDryga** [comment]
Hello, @mohitsahasrabudhe 👋. Can you submit a PR to fix this typo? :) I'd be happy to merge it!
